### ISSUE TITLE
Create a separate repo for blank_project

### ISSUE THREAD

**Issue by willemneal** [nearprotocol/near-shell#129] opened 2019-09-01 18:22 UTC
This gives the option to also fork the project.  If we make it a dependency for this than we can still just copy the files as we currently do.  Ideally it would be nice to have a selection of starting projects similar to NEARStudio.

**Comment by vgrichina** [comment] 2019-09-06 20:18
I think we should make it like other JS projects do (i.e. design for `npm init` / `yarn create` usage):

https://github.com/nearprotocol/near-shell/pull/133#issuecomment-528705928

**Comment by janedegtiareva** [comment] 2019-09-18 18:30
There are several discussions/issues for this. I am closing this one as a dupe of https://github.com/nearprotocol/near-shell/issues/144

**Closed by janedegtiareva** 2019-09-18 18:30 UTC
