### ISSUE TITLE
Invalid argument in near shell doesn't show any error

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/near-shell#206] opened 2019-11-25 22:38 UTC
A typo in the command lead to no error:
```
near create_accoount evm                                                                                
[WARNING] Didn't find config at /Users/cypress/projects/nearprotocol/near-evm/src/config, using default shell config
{ networkId: 'default',
  nodeUrl: 'https://rpc.nearprotocol.com',
  contractName: 'near-hello-devnet',
  walletUrl: 'https://wallet.nearprotocol.com' }
```

**Comment by janedegtiareva** [comment] 2019-11-27 23:00
duplicate of https://github.com/nearprotocol/near-shell/issues/50

**Closed by janedegtiareva** 2019-11-27 23:00 UTC
